version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: delivery_postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: delivery_app
      POSTGRES_USER: delivery_user
      POSTGRES_PASSWORD: delivery123

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
